apiVersion: v1
kind: Pod
metadata:
  name: worker-manual
  labels:
    app: worker
    type: manual
spec:
  containers:
  - name: worker
    image: demucs-worker:v2
    imagePullPolicy: Never
    env:
    - name: REDIS_HOST
      value: "redis"
    - name: REDIS_PORT
      value: "6379"
    - name: MINIO_ENDPOINT
      value: "minio-proj.minio-ns:9000"
    - name: MINIO_ACCESS_KEY
      value: "rootuser"
    - name: MINIO_SECRET_KEY
      value: "rootpass123"
    - name: MINIO_SECURE
      value: "false"
    - name: QUEUE_BUCKET
      value: "demucs-bucket"
    - name: OUTPUT_BUCKET
      value: "demucs-output"
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
      limits:
        memory: "8Gi"
        cpu: "2000m"
  restartPolicy: Always
  # Add command override to ensure it runs properly

